# Generated by Django 5.1 on 2024-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_rename_item_name_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='pasword',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='LostItem',
        ),
    ]
