# Generated by Django 5.1 on 2024-08-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_remove_item_student_remove_lostitem_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pasword',
            new_name='password',
        ),
    ]
