# Generated by Django 5.1 on 2024-08-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
