# Generated by Django 5.1 on 2024-08-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(max_length=15),
        ),
    ]
