# Generated by Django 5.1 on 2024-08-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0010_student_created_at_student_delete_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
