# Generated by Django 5.1 on 2024-08-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0012_alter_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
