# Generated by Django 5.1 on 2024-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0014_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/items/'),
        ),
    ]
