# Generated by Django 5.1 on 2024-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0015_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('others', 'Others')], default='', max_length=20),
        ),
    ]
