# Generated by Django 5.1 on 2024-08-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0016_remove_item_created_at_remove_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
