# Generated by Django 5.1 on 2024-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0018_alter_student_yearofstudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearofstudy',
            field=models.CharField(max_length=50),
        ),
    ]
