# Generated by Django 5.1 on 2024-08-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0019_alter_item_category_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lost_date', models.DateField()),
                ('lost_time', models.TimeField()),
                ('lost_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not Found')], default='not_found', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student')),
            ],
        ),
    ]
