# Generated by Django 5.1 on 2024-08-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0020_alter_student_email_alter_student_password_lostitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('found_date', models.DateField()),
                ('found_time', models.TimeField()),
                ('found_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('owner_verified', 'Owner Verified'), ('not_verified', 'Not Verified')], default='not_verified', max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student')),
            ],
        ),
    ]
