# Generated by Django 5.1 on 2024-08-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0021_founditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('dateofevent', models.DateField()),
                ('timeofevent', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
