# Generated by Django 5.1 on 2024-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0024_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
