# Generated by Django 5.1 on 2024-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0026_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='claims/')),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
