# Generated by Django 5.1 on 2024-08-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0027_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='found_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentApp.founditem'),
            preserve_default=False,
        ),
    ]
