# Generated by Django 5.1 on 2024-09-02 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0030_profile_rename_complaint_complaints_delete_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password',
            new_name='forget_password_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
