# Generated by Django 5.1 on 2024-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0031_rename_forget_password_profile_forget_password_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('dateofevent', models.DateField()),
                ('timeofevent', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventimages/')),
            ],
        ),
    ]
