#Generated by Django 5.1 on 2024-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0035_remove_item_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delete_status',
            field=models.CharField(choices=[(1, 'LIVE'), (0, 'DELETE')], default='LIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'live'), (0, 'delete')], default=1),
        ),
    ]
