# Generated by Django 5.1 on 2024-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0037_remove_item_delete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
    ]
