# Generated by Django 5.1 on 2024-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0038_item_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1),
        ),
    ]
