# Generated by Django 5.1 on 2024-09-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0041_alter_item_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_type',
            field=models.CharField(choices=[('LF', 'Lost and Found'), ('BS', 'Buy and Sell')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/'),
        ),
    ]
