# Generated by Django 5.1 on 2024-09-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0043_remove_student_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='found_date',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='found_location',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='found_time',
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to='studentApp.student'),
        ),
    ]
