# Generated by Django 5.1 on 2024-09-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0044_remove_founditem_found_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='claim',
            name='lost_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='claim',
            name='lost_location',
            field=models.CharField(default='college', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='lost_time',
            field=models.TimeField(default='00-00-00'),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
