# Generated by Django 5.1 on 2024-09-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0045_remove_claim_phone_number_claim_lost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='lost_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lost_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lost_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='claim',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
