# Generated by Django 5.1 on 2024-09-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0046_alter_claim_lost_date_alter_claim_lost_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
