# Generated by Django 5.1 on 2024-09-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0047_rename_phone_claim_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
