# Generated by Django 5.1 on 2024-09-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0048_rename_phone_number_claim_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
