# Generated by Django 5.1 on 2024-09-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0049_rename_phone_claim_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
