# Generated by Django 5.1 on 2024-09-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0053_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='studentApp.founditem'),
            preserve_default=False,
        ),
    ]
