# Generated by Django 5.1 on 2024-09-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0054_claim_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='student',
        ),
    ]
