# Generated by Django 5.1 on 2024-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0057_founditem_stat_lostitem_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='status',
        ),
    ]
