# Generated by Django 5.1 on 2024-10-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0059_remove_lostitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='buyer_user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='studentApp.item'),
            preserve_default=False,
        ),
    ]
