# Generated by Django 5.1 on 2024-10-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0060_rename_user_payment_buyer_user_remove_item_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='buyer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student'),
        ),
    ]
