# Generated by Django 5.1 on 2024-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0062_alter_payment_buyer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
