# Generated by Django 5.1 on 2024-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0063_item_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='paid',
            field=models.CharField(default='NOT PAID', max_length=20),
        ),
    ]
