# Generated by Django 5.1 on 2024-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0066_remove_item_user_item_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='u',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
