# Generated by Django 5.1 on 2024-10-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0068_alter_item_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.BooleanField(default=False),
        ),
    ]
