# Generated by Django 5.1 on 2024-10-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0069_payment_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_description',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_image',
            field=models.ImageField(default='items/book.jpg', upload_to='refund/'),
        ),
    ]
