# Generated by Django 5.1 on 2024-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0070_payment_refund_description_payment_refund_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='refund_description',
            field=models.TextField(default='n'),
        ),
    ]
