# Generated by Django 5.1 on 2024-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0072_alter_payment_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_date',
            field=models.CharField(default=122, max_length=10),
            preserve_default=False,
        ),
    ]
